default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: task_manager

test:
  <<: *default
  database: task_manager_test
