default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: root
  password: simple_password

development:
  <<: *default
  database: task_manager

test:
  <<: *default
  database: task_manager_test
