# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06132b33885beb0783811bedc6586476243dfb055e6b9845e091d370753b5ad5e21d2a3d78e6725128d02905c47594526155b34d7649af78adda478ae0b364b8

test:
  secret_key_base: 9e7ed8495d2d3ce92d90195708a96f8bffc5ffab2deb4c07522a4525d198976096e4bb7dbbeb81ec688066ceae6390f6a630bf02e118c2f9a0cc70b417d31002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
